package com.practicum.playlistmaker.common.ui

const val ARTWORK_URL_512_EXTRA = "ARTWORK_URL_512_EXTRA"
const val TRACK_NAME_EXTRA = "TRACK_NAME_EXTRA"
const val ARTIST_NAME_EXTRA = "ARTIST_NAME_EXTRA"
const val COLLECTION_NAME_EXTRA = "COLLECTION_NAME_EXTRA"
const val RELEASE_YEAR_EXTRA = "RELEASE_YEAR_EXTRA"
const val PRIMARY_GENRE_NAME_EXTRA = "PRIMARY_GENRE_NAME_EXTRA"
const val COUNTRY_EXTRA = "COUNTRY_EXTRA"
const val TRACK_TIME_EXTRA = "TRACK_TIME_EXTRA"
const val PREVIEW_URL_EXTRA = "PREVIEW_URL_EXTRA"
